version: 2

jobs:
    build:
        docker:
            - image: circleci/php:7.2.20
        steps:
            - checkout
            - run:
                command: |
                    mkdir -p ~$CIRCLE_TEST_REPORTS/phpunit
                    php vendor/bin/phpunit --log-junit ~$CIRCLE_TEST_REPORTS/phpunit/junit.xml --test-suffix=php/TestPlaceEvents.php --bootstrap vendor/autoload.php tests/.
                when: always

            - store_test_results:
                path: ~$CIRCLE_TEST_REPORTS/phpunit
            - store_artifacts:
                path: ~$CIRCLE_TEST_REPORTS/phpunit 
    test:
        docker:
            - image: circleci/php:7.2.20
        steps:
            - checkout
            - run:
                name: Run Tests
                command: |
                    mkdir -p ~$CIRCLE_TEST_REPORTS/phpunit
                    php vendor/bin/phpunit --log-junit ~$CIRCLE_TEST_REPORTS/phpunit/junit.xml --test-suffix=php/TestPlaceEvents.php --bootstrap vendor/autoload.php tests/.
                when: always
            - store_test_results:
                path: ~/phpunit
            - store_artifacts:
                path: ~/phpunit

workflow:
    version: 2.1
    
    orbs:
        coveralls: coveralls/coveralls@1.0.6

    coveralls_coverage:
        jobs:
            build:
                docker:
                    - image: circleci/node:12.16.1
                steps:
                    - checkout
                    - run:
                        command: sudo apt-get install npm
                    - run:
                        name: Update npm
                        command: sudo npm install -g npm@latest
                    - run:
                        name: Install and Make
                        command: npm install && make test-coverage
                    - coveralls/upload

workflows:
    version: 2
    build_and_test:
        jobs:
        - build
        - test


