version: 2
jobs:
    build:
        docker:
            - image: circleci/PHP:7.2.20
        steps:
            - checkout
            - run:
                command: |
                    mkdir -p ~/phpunit
                    phpunit --log-junit ~/phpunit/junit.xml tests
                when: always
            - store_test_results:
                path: ~/phpunit
            - store_artifacts:
                path: ~/phpunit 
    test:
        docker:
            - image: circleci/PHP:7.2.20
        steps:
            - checkout
            - run:
                command: |
                    mkdir -p ~/phpunit
                    phpunit --log-junit ~/phpunit/junit.xml tests
                when: always
            - store_test_results:
                path: ~/phpunit
            - store_artifacts:
                path: ~/phpunit 
workflows:
    version: 2
    build_and_test:
        jobs:
        - build
        - test

