version: 2
jobs:
    build:
        docker:
            - image: circleci/php:7.2.20
        steps:
            - checkout
            - run:
                command: |
                    mkdir -p ~/phpunit
                    php vendor/bin/phpunit --log-junit ~/phpunit/junit.xml --test-suffix=tests/UnitTesting/TestPlaceEvents.php --bootstrap vendor/autoload.php tests/.
                when: always
            - store_test_results:
                path: ~/phpunit
            - store_artifacts:
                path: ~/phpunit 
    test:
        docker:
            - image: circleci/php:7.2.20
        steps:
            - checkout
            - run:
                name: Run Tests
                command: |
                    mkdir -p ~/phpunit
                    php vendor/bin/phpunit --log-junit ~/phpunit/junit.xml --test-suffix=tests/UnitTesting/TestPlaceEvents.php --bootstrap vendor/autoload.php tests/.
                when: always
            - store_test_results:
                path: ~/phpunit
            - store_artifacts:
                path: ~/phpunit 
workflows:
    version: 2
    build_and_test:
        jobs:
        - build
        - test

