version: 2.1
orbs:
    coveralls: coveralls/coveralls@1.0.6
jobs:
    build:
        docker:
            - image: circleci/php:7.2.20
            - image: 'circleci/node:10.0.0'
        steps:
            - checkout
            - run:
                name: Update npm
                command: sudo npm install -g npm@latest
            - run:
                command: |
                    mkdir -p ~/phpunit
                    php vendor/bin/phpunit --log-junit ~/phpunit/junit.xml --test-suffix=php/TestPlaceEvents.php --bootstrap vendor/autoload.php tests/.
                when: always

            - run:
                name: Install and Make
                command: npm install && make test-coverage
            - coveralls/upload

            - store_test_results:
                path: ~/phpunit
            - store_artifacts:
                path: ~/phpunit 
    test:
        docker:
            - image: circleci/php:7.2.20
        steps:
            - checkout
            - run:
                name: Run Tests
                command: |
                    mkdir -p ~/phpunit
                    php vendor/bin/phpunit --log-junit ~/phpunit/junit.xml --test-suffix=php/TestPlaceEvents.php --bootstrap vendor/autoload.php tests/.
                when: always
            - store_test_results:
                path: ~/phpunit
            - store_artifacts:
                path: ~/phpunit 
workflows:
    version: 2
    build_and_test:
        jobs:
        - build
        - test

